// Additional books and authors data for the database

export const additionalBooks = [
  {
    id: 'book16',
    title: '1984',
    author: 'George Orwell',
    cover: 'https://images.unsplash.com/photo-1504610926078-a1611febcad3?q=80',
    rating: 4.7,
    description: 'The classic dystopian novel that explores the dangers of totalitarianism, surveillance, and thought control in a nightmarish future society.',
    genres: ['Dystopian', 'Science Fiction', 'Classic'],
    publishedDate: '1949-06-08',
  },
  {
    id: 'book17',
    title: 'Pride and Prejudice',
    author: 'Jane Austen',
    cover: 'https://images.unsplash.com/photo-1544947950-fa07a98d237f?q=80',
    rating: 4.5,
    description: 'A romantic novel centered on the turbulent relationship between Elizabeth Bennet, the daughter of a country gentleman, and Fitzwilliam Darcy, a rich aristocratic landowner.',
    genres: ['Classic', 'Romance', 'Historical Fiction'],
    publishedDate: '1813-01-28',
  },
  {
    id: 'book18',
    title: 'The Hobbit',
    author: 'J.R.R. Tolkien',
    cover: 'https://images.unsplash.com/photo-1528458909336-e7a0adfed0a5?q=80',
    rating: 4.6,
    description: 'A fantasy novel and children\'s book following the quest of Bilbo Baggins, a hobbit who is reluctantly swept into an epic quest to reclaim the Lonely Mountain from the dragon Smaug.',
    genres: ['Fantasy', 'Adventure', 'Classic'],
    publishedDate: '1937-09-21',
  },
  {
    id: 'book19',
    title: 'Harry Potter and the Philosopher\'s Stone',
    author: 'J.K. Rowling',
    cover: 'https://images.unsplash.com/photo-1626618012641-bfbca5a31239?q=80',
    rating: 4.8,
    description: 'The first novel in the Harry Potter series follows a young boy who discovers his identity as a wizard and begins his education at Hogwarts School of Witchcraft and Wizardry.',
    genres: ['Fantasy', 'Young Adult', 'Adventure'],
    publishedDate: '1997-06-26',
  },
  {
    id: 'book20',
    title: 'The Lord of the Rings',
    author: 'J.R.R. Tolkien',
    cover: 'https://images.unsplash.com/photo-1506466010722-395aa2bef877?q=80',
    rating: 4.9,
    description: 'An epic high-fantasy novel that follows the quest to destroy the One Ring, a powerful artifact created by the Dark Lord Sauron.',
    genres: ['Fantasy', 'Adventure', 'Epic'],
    publishedDate: '1954-07-29',
  },
  {
    id: 'book21',
    title: 'Brave New World',
    author: 'Aldous Huxley',
    cover: 'https://images.unsplash.com/photo-1597064647171-ef49da783f45?q=80',
    rating: 4.3,
    description: 'A dystopian novel set in a futuristic World State where citizens are environmentally engineered into an intelligence-based social hierarchy.',
    genres: ['Dystopian', 'Science Fiction', 'Classic'],
    publishedDate: '1932-01-01',
  },
  {
    id: 'book22',
    title: 'Crime and Punishment',
    author: 'Fyodor Dostoevsky',
    cover: 'https://images.unsplash.com/photo-1589829085413-56de8ae18c73?q=80',
    rating: 4.4,
    description: 'A novel that focuses on the mental anguish and moral dilemmas of Rodion Raskolnikov, an impoverished ex-student in Saint Petersburg who formulates a plan to kill an unethical pawnbroker.',
    genres: ['Classic', 'Literary Fiction', 'Psychological'],
    publishedDate: '1866-01-01',
  },
  {
    id: 'book23',
    title: 'The Catcher in the Rye',
    author: 'J.D. Salinger',
    cover: 'https://images.unsplash.com/photo-1598618443855-232ee0f819f6?q=80',
    rating: 4.2,
    description: 'The story of Holden Caulfield, a teenage boy who has been expelled from prep school and is wandering around New York City, struggling with his own adolescence and alienation.',
    genres: ['Literary Fiction', 'Coming of Age', 'Classic'],
    publishedDate: '1951-07-16',
  },
  {
    id: 'book24',
    title: 'One Hundred Years of Solitude',
    author: 'Gabriel García Márquez',
    cover: 'https://images.unsplash.com/photo-1533327325824-76bc4e62d560?q=80',
    rating: 4.4,
    description: 'A landmark of magical realism that tells the multi-generational story of the Buendía family, whose patriarch founds the town of Macondo, a metaphor for Colombia.',
    genres: ['Magical Realism', 'Literary Fiction', 'Historical Fiction'],
    publishedDate: '1967-05-30',
  },
  {
    id: 'book25',
    title: 'Wuthering Heights',
    author: 'Emily Brontë',
    cover: 'https://images.unsplash.com/photo-1518744386442-2d48ac47a7eb?q=80',
    rating: 4.2,
    description: 'A passionate, doomed love story set on the wild, stormy Yorkshire moors, following the intense, almost demonic love between Catherine Earnshaw and Heathcliff.',
    genres: ['Classic', 'Gothic', 'Romance'],
    publishedDate: '1847-12-19',
  },
  {
    id: 'book26',
    title: 'The Great Expectations',
    author: 'Charles Dickens',
    cover: 'https://images.unsplash.com/photo-1589998059171-988d887df646?q=80',
    rating: 4.1,
    description: 'The story of the orphan Pip and his growth and personal development through a series of relationships with a wide range of characters.',
    genres: ['Classic', 'Coming of Age', 'Literary Fiction'],
    publishedDate: '1861-01-01',
  },
  {
    id: 'book27',
    title: 'The Picture of Dorian Gray',
    author: 'Oscar Wilde',
    cover: 'https://images.unsplash.com/photo-1544947950-fa07a98d237f?q=80',
    rating: 4.3,
    description: 'A Gothic and philosophical novel about a vain young man who wishes that his portrait age rather than himself, leading to a life of immoral acts with no physical consequences to himself.',
    genres: ['Classic', 'Gothic', 'Philosophical Fiction'],
    publishedDate: '1890-07-01',
  },
  {
    id: 'book28',
    title: 'Moby-Dick',
    author: 'Herman Melville',
    cover: 'https://images.unsplash.com/photo-1580934138871-28daf05830de?q=80',
    rating: 4.1,
    description: 'The story of Captain Ahab\'s quest for revenge against Moby Dick, the white whale that bit off his leg at the knee on a previous voyage.',
    genres: ['Classic', 'Adventure', 'Sea Story'],
    publishedDate: '1851-10-18',
  },
  {
    id: 'book29',
    title: 'Don Quixote',
    author: 'Miguel de Cervantes',
    cover: 'https://images.unsplash.com/photo-1532187643603-ba119ca4109e?q=80',
    rating: 4.3,
    description: 'The story of a man who becomes so enchanted by reading chivalric romances that he loses his sanity and decides to become a knight-errant to revive chivalry and serve his nation.',
    genres: ['Classic', 'Satire', 'Adventure'],
    publishedDate: '1605-01-16',
  },
  {
    id: 'book30',
    title: 'War and Peace',
    author: 'Leo Tolstoy',
    cover: 'https://images.unsplash.com/photo-1610882648335-ced8fc8fa6b6?q=80',
    rating: 4.5,
    description: 'An epic novel that chronicles the history of the French invasion of Russia and the impact of the Napoleonic era on Tsarist society through the stories of five Russian aristocratic families.',
    genres: ['Classic', 'Historical Fiction', 'War'],
    publishedDate: '1869-01-01',
  },
];

export const additionalAuthors = [
  {
    id: 'author16',
    name: 'George Orwell',
    photo: 'https://images.unsplash.com/photo-1541534741688-6078c6bfb5c5?q=80',
    bio: 'George Orwell was an English novelist, essayist, journalist, and critic. His work is characterized by lucid prose, social criticism, opposition to totalitarianism, and support of democratic socialism.',
    bookCount: 9,
  },
  {
    id: 'author17',
    name: 'Jane Austen',
    photo: 'https://images.unsplash.com/photo-1589996448606-251491d1a0f9?q=80',
    bio: 'Jane Austen was an English novelist known primarily for her six major novels, which interpret, critique, and comment upon the British landed gentry at the end of the 18th century.',
    bookCount: 6,
  },
  {
    id: 'author18',
    name: 'J.R.R. Tolkien',
    photo: 'https://images.unsplash.com/photo-1568602471122-7832951cc4c5?q=80',
    bio: 'J.R.R. Tolkien was an English writer, poet, philologist, and academic. He is best known as the author of the classic high fantasy works The Hobbit, The Lord of the Rings, and The Silmarillion.',
    bookCount: 24,
  },
  {
    id: 'author19',
    name: 'J.K. Rowling',
    photo: 'https://images.unsplash.com/photo-1595959183082-7b570b7e08e2?q=80',
    bio: 'J.K. Rowling is a British author and philanthropist. She is best known for writing the Harry Potter fantasy series, which has won multiple awards and sold more than 500 million copies.',
    bookCount: 14,
  },
  {
    id: 'author20',
    name: 'Aldous Huxley',
    photo: 'https://images.unsplash.com/photo-1487309078313-fad80c3ec1e5?q=80',
    bio: 'Aldous Huxley was an English writer and philosopher. He wrote nearly fifty books, both novels and non-fiction works, as well as wide-ranging essays, narratives, and poems.',
    bookCount: 47,
  },
  {
    id: 'author21',
    name: 'Fyodor Dostoevsky',
    photo: 'https://images.unsplash.com/photo-1518020382113-a7e8fc38eac9?q=80',
    bio: 'Fyodor Dostoevsky was a Russian novelist, philosopher, short story writer, essayist, and journalist. His literary works explore human psychology in the troubled political, social, and spiritual atmospheres of 19th-century Russia.',
    bookCount: 12,
  },
  {
    id: 'author22',
    name: 'J.D. Salinger',
    photo: 'https://images.unsplash.com/photo-1620428268482-cf1851a36764?q=80',
    bio: 'J.D. Salinger was an American writer known for his novel The Catcher in the Rye, a classic of adolescent literature that has been translated into almost all of the world\'s major languages.',
    bookCount: 4,
  },
  {
    id: 'author23',
    name: 'Gabriel García Márquez',
    photo: 'https://images.unsplash.com/photo-1542821817-52343af06ae3?q=80',
    bio: 'Gabriel García Márquez was a Colombian novelist, short-story writer, screenwriter, and journalist, known for his magical realism style and considered one of the most significant authors of the 20th century.',
    bookCount: 26,
  },
  {
    id: 'author24',
    name: 'Emily Brontë',
    photo: 'https://images.unsplash.com/photo-1593104547489-5cfb3839a3ba?q=80',
    bio: 'Emily Brontë was an English novelist and poet who is best known for her only novel, Wuthering Heights, now considered a classic of English literature.',
    bookCount: 1,
  },
  {
    id: 'author25',
    name: 'Charles Dickens',
    photo: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?q=80',
    bio: 'Charles Dickens was an English writer and social critic. He created some of the world\'s best-known fictional characters and is regarded by many as the greatest novelist of the Victorian era.',
    bookCount: 15,
  },
  {
    id: 'author26',
    name: 'Oscar Wilde',
    photo: 'https://images.unsplash.com/photo-1564564321837-a57b7070ac4f?q=80',
    bio: 'Oscar Wilde was an Irish poet and playwright known for his wit, flamboyance, and imprisonment for homosexuality. His novel The Picture of Dorian Gray and plays like The Importance of Being Earnest are considered classics.',
    bookCount: 11,
  },
  {
    id: 'author27',
    name: 'Herman Melville',
    photo: 'https://images.unsplash.com/photo-1504257432389-52343af06ae3?q=80',
    bio: 'Herman Melville was an American novelist, short story writer, and poet of the American Renaissance period. His best-known works include Moby-Dick and Typee.',
    bookCount: 10,
  },
  {
    id: 'author28',
    name: 'Miguel de Cervantes',
    photo: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?q=80',
    bio: 'Miguel de Cervantes was a Spanish writer widely regarded as the greatest writer in the Spanish language and one of the world\'s pre-eminent novelists. His masterpiece Don Quixote has been translated into over 140 languages.',
    bookCount: 17,
  },
  {
    id: 'author29',
    name: 'Leo Tolstoy',
    photo: 'https://images.unsplash.com/photo-1548372290-8d01b6c8e78c?q=80',
    bio: 'Leo Tolstoy was a Russian writer who is regarded as one of the greatest authors of all time. His major works include War and Peace and Anna Karenina.',
    bookCount: 12,
  },
];

// Additional reviews for the new books
export const additionalReviews = [
  {
    id: 'review9',
    bookId: 'book16',
    bookTitle: '1984',
    userName: 'Alex Turner',
    userId: 'user9',
    rating: 5,
    content: 'A chilling masterpiece that remains incredibly relevant today. Orwell\'s vision of a totalitarian future feels more prophetic with each passing year. The concepts of doublethink, thoughtcrime, and Big Brother have become part of our cultural vocabulary for good reason.',
    date: '2023-05-17',
  },
  {
    id: 'review10',
    bookId: 'book17',
    bookTitle: 'Pride and Prejudice',
    userName: 'Olivia Parker',
    userId: 'user10',
    rating: 5,
    content: 'Austen\'s wit and social commentary shine in this timeless romance. Elizabeth Bennet is one of literature\'s most delightful heroines - intelligent, spirited, and unwilling to compromise her values. Her relationship with Darcy evolves beautifully throughout the novel.',
    date: '2023-06-22',
  },
  {
    id: 'review11',
    bookId: 'book18',
    bookTitle: 'The Hobbit',
    userName: 'William Nelson',
    userId: 'user11',
    rating: 4,
    content: 'A wonderful adventure story with rich world-building and memorable characters. Bilbo\'s growth from reluctant homebody to brave adventurer is captivating. The perfect introduction to Tolkien\'s Middle-earth before diving into the more complex Lord of the Rings trilogy.',
    date: '2023-07-10',
  },
  {
    id: 'review12',
    bookId: 'book20',
    bookTitle: 'The Lord of the Rings',
    userName: 'Sophie Reynolds',
    userId: 'user12',
    rating: 5,
    content: 'An epic masterpiece that defined modern fantasy literature. Tolkien created not just a story but an entire world with its own languages, histories, and mythologies. The themes of friendship, courage, and the corrupting influence of power resonate deeply.',
    date: '2023-08-15',
  },
  {
    id: 'review13',
    bookId: 'book21',
    bookTitle: 'Brave New World',
    userName: 'Jackson Miller',
    userId: 'user13',
    rating: 4,
    content: 'Huxley\'s dystopia is particularly unsettling because it doesn\'t rely on fear and brutality, but on pleasure and distraction to control its citizens. The contrast between the "savage" John and the "civilized" World State raises profound questions about what truly makes a good society.',
    date: '2023-09-05',
  },
  {
    id: 'review14',
    bookId: 'book24',
    bookTitle: 'One Hundred Years of Solitude',
    userName: 'Isabella Ramirez',
    userId: 'user14',
    rating: 5,
    content: 'A breathtaking achievement in magical realism. Márquez weaves generations of the Buendía family into a tapestry that reflects the complex history of Colombia and Latin America. The cyclical nature of time and the inevitable repetition of history are presented with both tragedy and humor.',
    date: '2023-10-18',
  },
  {
    id: 'review15',
    bookId: 'book27',
    bookTitle: 'The Picture of Dorian Gray',
    userName: 'Ethan Brooks',
    userId: 'user15',
    rating: 4,
    content: 'Wilde\'s only novel is a fascinating examination of beauty, corruption, and moral decay. The premise is brilliant: a man remains eternally youthful while his portrait ages and reflects the ugliness of his sins. Wilde\'s aphorisms are as delightful as the story is disturbing.',
    date: '2023-11-03',
  },
  {
    id: 'review16',
    bookId: 'book30',
    bookTitle: 'War and Peace',
    userName: 'Grace Thompson',
    userId: 'user16',
    rating: 5,
    content: 'An immense and immersive reading experience that deserves its reputation as one of the greatest novels ever written. Tolstoy\'s ability to shift between intimate domestic scenes and sprawling battle sequences is remarkable. The characters feel so real that finishing the book feels like saying goodbye to friends.',
    date: '2023-12-12',
  },
]; 